#!/bin/sh

PARTS=`LANG=C svn info | grep URL | awk '{print $2;}' | sed -e s:^.*/svn/asterisk-gui/be/:: | sed -e 's:/: :g'`
BETA=0
BRANCH=0
TEAM=0
TAG=0

REV=`svnversion -c . | cut -d: -f2`

if [ "${PARTS}" = "trunk" ]
then
    echo "gui_version = 'SVN-branches-2.0-r${REV}';"
    exit 0
fi

for PART in $PARTS
do
  if [ ${BETA} != 0 ]
  then
      RESULT="${RESULT}-${PART}"
      break
  fi

  if [ ${TAG} != 0 ]
  then
      RESULT="${PART}"
      break
  fi

  if [ ${BRANCH} != 0 ]
  then
      RESULT="${RESULT}-${PART}"
      break
  fi

  if [ ${TEAM} != 0 ]
  then
      RESULT="${RESULT}-${PART}"
      continue
  fi

  if [ "${PART}" = "betas" ]
  then
      BETA=1
      RESULT="beta"
      continue
  fi

  if [ "${PART}" = "branches" ]
  then
      BRANCH=1
      RESULT="branch"
      continue
  fi

  if [ "${PART}" = "tags" ]
  then
      TAG=1
      continue
  fi

  if [ "${PART}" = "team" ]
  then
      TEAM=1
      continue
  fi
done

echo -n "gui_version = '"

if [ ${TAG} != 0 ]
then
    echo -n "${RESULT}"
else
    echo -n "SVN-${RESULT##-}-r${REV}"
fi

echo "';"
