#!/bin/sh
SYSINFO_OUTPUT="/var/lib/asterisk/static-http/config/sysinfo_output.html"

UNAME="`uname -a`"
/bin/echo "<div id=si_uname>$UNAME</div>" > $SYSINFO_OUTPUT

UPTIME="`uptime`"
/bin/echo "<div id=si_uptime>$UPTIME</div>" >> $SYSINFO_OUTPUT

TODAY="`date`"
/bin/echo "<div id=si_date>$TODAY</div>" >> $SYSINFO_OUTPUT

HOSTNAME="`hostname`"
/bin/echo "<div id=si_hostname>$HOSTNAME</div>" >> $SYSINFO_OUTPUT


